### ISSUE TITLE
[PocketGo2 v2 / RG350P] Game preview picture is automatically updated when using "Save state"

### ISSUE THREAD

**Issue by DrUm78** [goldmojo/fba-sdl#1]
Hardware: PocketGo2 v2 / RG350P
O/S: Rogue FW 1.0.9 for PocketGo2 v2 / Rogue FW 1.7.10 for RG350
Software: FinalBurnAlpha_2020-01-29-.44_alias_cmdline_gameconfig_controls_samples.opk

When saving a game state, it automatically sets it as the game preview in the launcher, even if the user did not chose "Set as preview" option. Only manual "Save as preview" should do that. The bug occurred with the previous version as well.

Please find the video footage:
https://drive.google.com/file/d/14GTLh6FYyAOG9cW1U2IVqOu-Tk_AV3Vz/view?usp=sharing

Steps to reproduce:
1. Launch any game you do not have any save state on
2. Press L+R+Start to enter option menu
3. Select "Save state" (any slot)
4. Exit game
5. Notice that your game preview has been updated with the one of your save state (save state previews are located into "/usr/local/home/.fba/saves" and are named like "xmcota0p.png" for "X-Men Children Of The Atom" for instance)

**Comment by goldmojo** [comment]
Could you check the content of this folder : /usr/local/home/.fba/previews ?

If a preview is set in this folder (for example : /usr/local/home/.fba/previews/1941.png), it will not be overwritten by the  /usr/local/home/.fba/saves one.

If your previews folder is not set, I would suggest to set it with your previews in order to solve this "issue".

**Comment by DrUm78** [comment]
Ok I found the issue... It only occurs when your game preview is in bmp format! bmp is recognized and displayed correctly but I guess that your preview pic check in your code is made for png extension only, right? So, if I rename all my bmp into png, that solves the issue (need to find a batch for that as I have hundreds of them though).

As bmp is read correctly, maybe you could handle this format as well as png.

**Comment by goldmojo** [comment]
Just to be perfectly clear, this is not my code but FBA team's code.

I just add a quick look, FBA is looking for .png or .bmp files in lower case.
Could you check the case of your ".bmp" extension ?

**Comment by DrUm78** [comment]
They all are in bmp lower case. Strange then. Can you try with a bmp file and confirm that you have the issue as well?

**Comment by goldmojo** [comment]
OK, same here and found what is happening, algorithm is as follow when loading previews:

1. Look first for png, then for bmp
2. If preview.png not found, then look for save.png
3. Only if no previews or save, looks for bmp ...

I will change in order to search for any preview format first, then saves only.

**Comment by DrUm78** [comment]
Yeah that sounds logical now, good news. 👍

**Comment by goldmojo** [comment]
I have sent a PM to you using dingoonity forum mailbox with a beta test version in order to confirm the fix.
If the fix is ok, it will be in the next release.

**Comment by DrUm78** [comment]
Great, I will test it for sure, thanks.

**Comment by DrUm78** [comment]
Fixed and verified in fba-previews_fix-BETA.opk. :)

**Comment by goldmojo** [comment]
OK, I will publish it then.
Thank you for testing !
